name: Install Coolify and Expose with Ngrok

on: [push]

jobs:
  install-and-expose:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Coolify
      run: |
        curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash

    - name: Set up Ngrok
      run: |
        # Install Ngrok
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc > /dev/null &&
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list &&
        sudo apt-get update && sudo apt-get install ngrok

        # Authenticate Ngrok
        ngrok config add-authtoken 2r2ZWHLk6CyOqaTGngTgdxGpIlt_7mhbgiYw4vJaR8aA1BjPk
        # Start Ngrok tunnel
        ngrok http 3000 > /dev/null &

    
